#### general settings
name: DANv2x4_setting1
use_tb_logger: true
model: blind
distortion: sr
scale: 4
gpu_ids: [0]
pca_matrix_path: ../../../pca_matrix/DCLS/pca_matrix.pth

degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 4.0
  rate_iso: 1.0
  random_disturb: false

#### datasets
datasets:
  train:
    name: train
    mode: GT
    dataroot_GT: /root/autodl-tmp/DiffBSR/load/train

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    GT_size: 256
    LR_size: 64
#    use_flip: true
#    use_rot: true
    use_flip: false
    use_rot: false
    color: RGB
  val:
    name: val_DCLS
    mode: LQGT
    dataroot_GT: /root/autodl-tmp/DCLS/codes/data/load/val_DCLS/x4HRblur.lmdb
    dataroot_LQ: /root/autodl-tmp/DCLS/codes/data/load/val_DCLS/x4LRblur.lmdb

#### network structures
network_G:
  which_model_G: DAN
  setting:
    nf: 64
    nb: 10
    ng: 5
    input_para: 10
    loop: 4
    kernel_size: 21

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_E: !!float 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  #niter: 800000
  niter: 50000
  warmup_iter: -1  # no warm up
  #lr_steps: [200000, 400000, 600000]
  lr_steps: [12500, 25000, 37500]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  #val_freq: !!float 2.5e3
  val_freq: 500

#### logger
logger:
  print_freq: 20
  #save_checkpoint_freq: !!float 2.5e3
  save_checkpoint_freq: 500
